### ISSUE TITLE
Bot is offline (again?)

### ISSUE THREAD

**Issue by smaartscz** [shiv213/ImposterBot#3]
Hi!
I wanted to try ImposterBot but I can't get him to be online.
Is bot dead? And is there any way to self host him?

Thanks for answer! :)

**Comment by shiv213** [comment]
hey @smaartscz ! ImposterBot is deprecated now, but you can self-host `index.js` in the root directory to run ImposterBot yourself.

**Comment by smaartscz** [comment]
Oh, okay!
Thanks and good luck!
